version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: hrms-db
    restart: always
    environment:
      MYSQL_DATABASE: hr_management_system_db
      MYSQL_ROOT_PASSWORD: bintangmada
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: hrms-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hr_management_system_db?useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=xxxx
      - SPRING_DATASOURCE_PASSWORD=yyyy
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
