spring.application.name=hr_management_system

# ===============================
# DATABASE PROPERTIES HR MANAGEMENT SYSTEM
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hcm_db?useSSL=false&serverTimezone=Asia/Jakarta}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:xxxyyy}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
